ongr_filter_manager:
    managers:
        search_list:
            filters:
                - channel
                - enabled
                - taxon
                - priceRange
                - locale
                - paginator
                - search
                - attributes
                - sort
            repository: es.manager.default.product
    filters:
        channel:
            type: choice
            request_field: channel
            document_field: channel_code
        enabled:
            type: choice
            request_field: enabled
            document_field: enabled
        taxon:
            type: choice
            request_field: taxon
            document_field: taxons.code
        priceRange:
            type: range
            request_field: price
            document_field: price.amount
            options:
                inclusive: true
        locale:
            type: choice
            request_field: locale
            document_field: locale_code
        paginator:
            type: sylius_elastic_search.custom_pager
            document_field: ~
            request_field: page
            options:
                limit: 10
                max_pages: 20
        attributes:
            type: multi_dynamic_aggregate
            request_field: attributes
            document_field: attributes>attributes.value
            options:
                name_field: attributes.name
        search:
            type: match
            request_field: search
            document_field: name,description,attributes>attributes.value
            options:
                operator: and
        sort:
            type: sort
            request_field: sort
            document_field: ~
            options:
                choices:
                    price_asc: { field: price.amount, default: false, order: asc }
                    price_desc: { field: price.amount, default: false, order: desc }
                    name_asc: { field: name, default: false, order: asc }
                    name_desc: { field: name, default: false, order: desc }
